version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${DB_USER:-app_user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-app_password}
      POSTGRES_DB: ${DB_NAME:-app_db}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-app_user} -d ${DB_NAME:-app_db}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app_network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_backend
    env_file:
      - .env  # Load from .env file
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      PYTHONPATH: /app
      PORT: 8080
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./app:/app/app
    networks:
      - app_network
    restart: unless-stopped
    command: sh -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8080"

volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge